### ISSUE TITLE
Docker image don't work 

### ISSUE THREAD

**Issue by BillMeyerRSA** [jasonelle/jasonbase#1]
I get this on startup

Fatal error: Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'docker.fields' doesn't exist (in /var/www/html/wire/core/WireSaveableItems.php line 170) #0 /var/www/html/wire/core/WireSaveableItems.php(170): PDOStatement->execute() #1 /var/www/html/wire/core/Wire.php(383): ProcessWire\WireSaveableItems->___load(Object(ProcessWire\FieldsArray)) #2 /var/www/html/wire/core/WireHooks.php(723): ProcessWire\Wire->_callMethod('___load', Array) #3 /var/www/html/wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Fields), 'load', Array) #4 /var/www/html/wire/core/Fields.php(132): ProcessWire\Wire->__call('load', Array) #5 /var/www/html/wire/core/ProcessWire.php(466): ProcessWire\Fields->init() #6 /var/www/html/wire/core/ProcessWire.php(422): ProcessWire\ProcessWire->initVar('fields', Object(ProcessWire\Fields)) #7 /var/www/html/wire/core/ProcessWire.php(209): ProcessWire\ProcessWire->load(Object(ProcessWire\Config)) #8 /var/www/html/index.php(52): ProcessWire\ProcessWire->__construct(Obj in /var/www/html/index.php on line 64

**Comment by BillMeyerRSA** [comment]
Modify pw.sql file to look like this

[pw.sql.txt](https://github.com/jasonelle/jasonbase/files/3526558/pw.sql.txt)
